[package]
name = "KMeans"
version = "0.1.0"
authors = ["Samuel Beausoleil <samuel.beausoleil@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rgb = "0.8.25"
rand = "0.8.2"
